config/routes.rb
Winorder::Application.routes.draw do
  resources :push_events do
    collection do 
      post "pipedrive_endpoint"
    end
  end
  resources :projects do
    collection do
      post "pipedrive_endpoint"
    end
    member do 
      get "load_data"
    end
  end
  root "push_events#index"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/models/project.rb
require "google/api_client"
require "google_drive"
class Project < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  belongs_to :user
  
  def load_from_yml
    list = YAML::load_file('results.yml')
    list.each do |el|
      Project.create(:data => el.to_s, :name => "#{el[:firstname]} #{ el[":lastname"] } ")
    end
  end
  
  def load_sheet_data
    drive = PullGoogleSheet.new
    sheet_data = drive.pull(self.name)
    self.data["sheet_data"] = sheet_data.to_json
    self.save
  end
  
  def load_pipedrive_data
    drive = PipedriveDealer.new(ENV["PIPEDRIVE_TOKEN"], self.name)
    pipedrive_data = drive.get_deal_data
    self.data["pipedrive_data"] = pipedrive_data.to_json 
    self.save
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :load_data]
 # before_action :authenticate_user!
  skip_before_filter  :verify_authenticity_token, only: [:pipedrive_endpoint]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @arr = JSON.parse(@project.data["sheet_data"]) rescue []
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pipedrive_endpoint
    binding.pry
     project = Project.find_or_create_by_pipedrive_id(params["meta"]["id"])   
     project["data"]["pipedrive_data"] = params.to_json
     project.save
    head :ok, content_type: "text/html"
  end
  def load_data
    result = @project.load_sheet_data
             @project.load_pipedrive_data  
    respond_to do |format|
      if result == true
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id, :data)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "form-horizontal project" } do |f| %>

    <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@project[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%= error_span(@project[:user_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :data, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :data, :class => 'form-control' %>
    </div>
    <%= error_span(@project[:data]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            projects_path, :class => 'btn btn-default' %>

<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h3> Doctors list </h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%#= model_class.human_attribute_name(:id) %></th>
      <th><%#= model_class.human_attribute_name(:name) %></th>
      <th><%#= model_class.human_attribute_name(:created_at) %></th>
      <th><%#=t '.actions', :default => t("helpers.actions") %></th>
      <th><%#=t '.actions', :default => t("helpers.actions") %></th>
      <th><%#=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <% if project.data[":email"].size >3 and project.data[":address"].size > 20 %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><strong><%= project.name %> </strong></td>
        <td>  <%= project.data[":email"] %></td>
        <td> 
        <%= project.data[":titles"] %> 
        <hr>
        <%= project.data[":enrollment"] %> 
        <hr />
        <%= project.data[":specialties"] %> 
        
        </td>
        <td>  <%= project.data[":address"] %></td>
        
        
        <td>  <%= time_ago_in_words(project.created_at) %> ago  </td>
        <td>
          <%#= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-default btn-xs' %>
          <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
<% end %>
  </tbody>
</table>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  <%= link_to  load_data_project_path(@project), :class=> "btn btn-primary" do %>
      <i class="fa fa-refresh"></i> Refresh Data
  <% end %>
</div>
<!--iframe class="col-md-12"  src="https://docs.google.com/spreadsheets/d/1kyWb9jylT61uW9GptKzskrew1jfMCxesct7E7O7SYhs/pub?gid=1951684584&single=true&output=pdf"></iframe>
<iframe src="https://docs.google.com/spreadsheets/d/1kyWb9jylT61uW9GptKzskrew1jfMCxesct7E7O7SYhs/pubhtml?gid=573729869&amp;single=true&amp;widget=true&amp;headers=false"></iframe--!>
  <div class="row">
    <div class="col-md-8">
        <dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @project.name %></dd>
  
</dl>
<%- @arr.each do |row| %>
  <div class="row well">
  <div class="col-md-4">
    <%= image_tag row.first, :class=>"img-thumbnail" %>
  </div>
  <div class="col-md-4">
    <span class=""><%=raw row[1] %> </span>   
  </div>
  <div class="col-md-4">
    <span><%=raw row[2] %> </span>   
  </div>
  </div>
<% end %>
</div>
<div class="col-md-4">
<div class="panel panel-info">
  <div class="panel-heading"><strong>Pipedrive Deal Info</strong></div>
  <div class="panel-body">
      <%- if @project.data["pipedrive_data"] and @project.data["pipedrive_data"]!= "null" %>
        <dl class="dl-horizontal">
          <%- JSON.parse(@project.data["pipedrive_data"]).first["details"].each do |key,value| %>
          
          <dt><strong><%= key %>:</strong></dt>
          <dd><%= value %></dd>
        <% end %>
        </dl>
        <% end %>
      
  </div>
</div>
      </div>
      </div>
<%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>